### ISSUE TITLE
display resolutions

### ISSUE THREAD

**Issue by twist84** [thefeeltrain/thefeeltrain.github.io#1]
Would you kindly add all the in game display resolutions please? as some of us play at 1600x900.

Thanks

**Comment by TheFeelTrain** [comment]
I'll get to work on that. The project was pretty much dead since the guy who was implementing it in game left but I see that people are still working on it so I guess I'll continue development.

**Comment by twist84** [comment]
Thank you, its nice to know some developers understand the community.

**Comment by Shadowfita** [comment]
Yes, it would be amazing to have extra resolutions for it, I took your menu and did this with it: http://192.99.124.170/ .

The server browser is fully functional :3, I tried to add resolutions myself and failed... I also sent you an email yesterday about it.

**Comment by Shadowfita** [comment]
Infact, do you think you could add an option to auto-scale depending on what the browser/client is re-sized to? If possible.

As well as the resolutions.

**Comment by TheFeelTrain** [comment]
Could you fork the repo and add your changes, then submit a pull request so I can update it? Your server browser is awesome. As soon as that happens I'll work on auto-scaling and adding all the resolutions.

**Comment by Shadowfita** [comment]
Yeah, did you get my reddit pm?

**Comment by TheFeelTrain** [comment]
Just checked... No I don't use Skype. Right here works for communication though

**Comment by Shadowfita** [comment]
Okay, you need to know my javascript knowledge is about 4 days worth, I started working on the browser knowing nearly nothing... on that note I have no idea how to fork a repo and submit a pull request, haha.

**Comment by Shadowfita** [comment]
I've never used github.

**Comment by TheFeelTrain** [comment]
Haha, alright. Could you upload the files you changed to Mega/Dropbox/Google Drive so I could use them then?

**Comment by twist84** [comment]
zip it and i'll pull

**Comment by Shadowfita** [comment]
Will do, one sec.

**Comment by twist84** [comment]
What files did you change?

**Comment by Shadowfita** [comment]
dewrito.css and dewrito.js and index.html

**Comment by twist84** [comment]
pastebin them

**Comment by Shadowfita** [comment]
https://mega.co.nz/#!EtY2DLKa!oh3SXaeje1V2b5zvTaafqzHcDqJFAI7SiygXtfoQ-fQ

There's a lot of unused code in dewrito.js and it's a bit of a mess but yeah.(from my tests and stuff)

**Comment by TheFeelTrain** [comment]
You need to include the decryption key with the url

**Comment by Shadowfita** [comment]
Yeah I edited it.

**Comment by TheFeelTrain** [comment]
Implementing it now. I'll start working on resolutions tomorrow. It's 12am and I have work at 8 tomorrow so I have to get to bed.

**Comment by Shadowfita** [comment]
Sounds good, so you'll be adding the resolution choices and an autoscale?

**Comment by TheFeelTrain** [comment]
Yes.

**Comment by Shadowfita** [comment]
Awesome, I look forward to it.

**Comment by twist84** [comment]
GET http://thefeeltrain.github.io/js/jquery.min.map 404 (Not Found)
not sure why but i get that error the http://thefeeltrain.github.io/ whilst trying to browse servers

**Comment by TheFeelTrain** [comment]
Try using https, but it looks like the ElDewrito server is down right now anyways. 
https://eldewrito-masterserver-personality.c9.io/list

**Comment by Shadowfita** [comment]
The master server was changed to http://192.99.124.162/list

**Comment by TheFeelTrain** [comment]
It works on my pc locally, but on github since the server is over http instead of https chrome throws a fit

**Comment by Shadowfita** [comment]
What errors? I'm having the same issue... just can't remember if you're as updated as mine is at the moment.

**Comment by TheFeelTrain** [comment]
If you use http://thefeeltrain.github.io/ it works fine but https://thefeeltrain.github.io/ does not.

**Comment by Shadowfita** [comment]
That's still trying to connect to the old master server for me.

**Comment by TheFeelTrain** [comment]
Refresh a couple times it's updated

**Comment by Shadowfita** [comment]
There we go, yeah... I'm assuming it's because https doesn't allow non-secure urls? possibly.

**Comment by Shadowfita** [comment]
http://puu.sh/iGlpZ/2d602cd4b8.txt

that one brings more order to server names and filters out html tags, not sure how github works but maybe you can see the differences.

_edit_
It also fixes "DEFAULTGUARDIAN" not showing a picture.

**Comment by TheFeelTrain** [comment]
I get "Uncaught TypeError: Cannot read property 'map' of undefined" when trying to click on the server to join the lobby

**Comment by Shadowfita** [comment]
Yeah, not sure why that's happening. It works after a refresh.

**Comment by TheFeelTrain** [comment]
It seems to work fine regardless but that's weird.

**Comment by Shadowfita** [comment]
Yeah, it might be storing ghost servers(?)

**Comment by Shadowfita** [comment]
It shouldn't be doing that though.

**Comment by TheFeelTrain** [comment]
For me joining the lobby works about 1/2 the time. Interesting.

**Comment by Shadowfita** [comment]
Joining works if the server isn't full. if it's 16/16 nothing happens.

**Comment by TheFeelTrain** [comment]
Oh yeah. I forgot I set it up like that.

**Comment by Shadowfita** [comment]
Haha. I think it's good to have it like that.

**Comment by TheFeelTrain** [comment]
Joining a full server wouldn't make sense. I think I'll add a dialogue box that says the server is full though to prevent future confusion

**Comment by Shadowfita** [comment]
Alrighty, just a normal alert("full"); ?

**Comment by TheFeelTrain** [comment]
No one styled to Reach's theme.

**Comment by Shadowfita** [comment]
Awesome.

**Comment by Shadowfita** [comment]
I can't remember but in your original menu could you change the gametype?

**Comment by TheFeelTrain** [comment]
No I never got around to it. I'll do that now.

**Comment by Shadowfita** [comment]
Great.

**Comment by Shadowfita** [comment]
Do you want a list of gametypes?

**Comment by TheFeelTrain** [comment]
Yeah that would make things easier

**Comment by Shadowfita** [comment]
http://puu.sh/iGsYL/a736bc69d0.txt

There are more slayer types but they're blank ingame.

**Comment by Shadowfita** [comment]
the -text indicates a subitem

**Comment by TheFeelTrain** [comment]
More resolutions and auto scaling are now working for the most part. The back button disappears for me on Chrome but I'm looking into it. You can still click it but it's invisible for some reason.

**Comment by Shadowfita** [comment]
Awesome! looking great so far.

**Comment by Shadowfita** [comment]
I have a back button

**Comment by TheFeelTrain** [comment]
I just fixed it.

**Comment by Shadowfita** [comment]
Ah, haha. Nice!

**Comment by TheFeelTrain** [comment]
For some reason it went behind the background video so I just set the background's z-index to -1 and that surprisingly worked

**Comment by Shadowfita** [comment]
Huh, alrighty then.

When in the server browser it seems that it's not loading map images for me.

**Comment by TheFeelTrain** [comment]
Working fine for me. I see Rockets on Guardian

**Comment by Shadowfita** [comment]
Strange, http://puu.sh/iGBF2/e67927a70a.jpg

**Comment by TheFeelTrain** [comment]
Right click -> inspect element -> Then see what url it's trying to load

**Comment by Shadowfita** [comment]
http://thefeeltrain.github.io/img/maps/Guardian.png

**Comment by TheFeelTrain** [comment]
Oh it should be loading GUARDIAN.png I'll try to fix it.

**Comment by Shadowfita** [comment]
It shouldn't be case sensitive, I changed it so that it would display 'Guardian' or 'Edge' in the server browser.

**Comment by TheFeelTrain** [comment]
It is case sensitive because that's how web servers work unfortunately.

**Comment by Shadowfita** [comment]
It was working fine on my windows server using xampp o:

**Comment by Shadowfita** [comment]
Probably different.

**Comment by TheFeelTrain** [comment]
Yeah it works fine on my local server too but once it reaches Github it gets upset

**Comment by TheFeelTrain** [comment]
It's fixed now. Just had to use .toUpperCase() on the file name.

**Comment by Shadowfita** [comment]
There we go, awesome.

**Comment by Shadowfita** [comment]
The map image isn't showing up when I join a lobby either

**Comment by TheFeelTrain** [comment]
Ah same issue there too I'm on it.

**Comment by twist84** [comment]
so this happens 
https://db.tt/RzxtcHha

**Comment by Shadowfita** [comment]
reset your cookies for thefeeltrain.github.io

**Comment by thefeeltrain** [comment]
Yeah I know I need to make a reset resolution button

**Comment by twist84** [comment]
fixed

**Comment by TheFeelTrain** [comment]
That is something specific to your machine. Could be an extension.

**Comment by TheFeelTrain** [comment]
Or not

**Comment by Shadowfita** [comment]
He just needed to reset his cookies for it :3 it had his old settings saved.

**Comment by twist84** [comment]
yup

**Comment by Shadowfita** [comment]
would it be possible to reset the cookies for the page on load? so that when people who have visited previously load it up it doesnt screw up with the new changes.

**Comment by Shadowfita** [comment]
This happens when overlaying the game onto halo online http://puu.sh/iGE3d/ea298bd059.jpg

**Comment by TheFeelTrain** [comment]
What are you using to overlay it? Do you know what layout engine it uses? (Blink, Webkit, Gecko, etc.)

**Comment by Shadowfita** [comment]
Pretty sure it's awesomium.

**Comment by TheFeelTrain** [comment]
Alright I'm pretty sure that's blink, not sure why the rendering would be messed up like that

**Comment by TheFeelTrain** [comment]
If it's not too much, could you get all of the descriptions for the gametypes?

**Comment by Shadowfita** [comment]
Oh sorry, didn't see that. Uhh, I can try.

**Comment by Shadowfita** [comment]
http://puu.sh/iHOae/91d56e7a9c.txt

there you go, includes the parent and subitem descriptions, for example you choose slayer it says kill your enemies etc then you click that and choose slayer team slayer and all that.

**Comment by Shadowfita** [comment]
http://puu.sh/iHP1X/eaa5c950d8.jpg

It seems that in order for it to work it needs to be placed in the bottom right corner which is strange.

**Comment by Shadowfita** [comment]
or the bottom left, or even the center.

**Comment by Shadowfita** [comment]
or just the bottom center, sorry it's the bottom center... sorry about the spam, heh.

**Comment by Shadowfita** [comment]
Vicelio said that it being off centered here http://puu.sh/iHP1X/eaa5c950d8.jpg might be his fault(guy working on the html overlay) so just leave it as is for now I guess.

**Comment by Shadowfita** [comment]
Never mind the resolution is fixed, when did you fix it? haha.

I downloaded the latest github build.

https://imgrush.com/NFBa0Okzh6JS

**Comment by TheFeelTrain** [comment]
I think it was a problem with the CSS that I fixed last night. It looks like your logo is missing, though :/

**Comment by TheFeelTrain** [comment]
But anyways thanks for getting those gametype descriptions they're in the menu now. And if you need to reset cookies you can just click the version (the eldewrito-beta in the bottom right)

**Comment by TheFeelTrain** [comment]
I also managed to find a Halo 4 menu background. If only I could find Halo 2 and 3 all of the backgrounds would be there.

**Comment by Shadowfita** [comment]
Theres an issue with uhm, the way you have it it's get "//:" + ip that doesnt work with the overlay. it needs to be "http://" and for connecting with the overlay it needs to be callbacks.connect(ip); rather than the getlaunch.click(ip); stuff.

**Comment by TheFeelTrain** [comment]
Alright, I re-added the http://. Could you download the latest dewrito.js and change the callbacks stuff? I'm not good with that sort of thing/don't know how awesomium works.

**Comment by Shadowfita** [comment]
Will do.

**Comment by Shadowfita** [comment]
http://puu.sh/iHTem/b8ad47b036.txt

updated js.

**Comment by TheFeelTrain** [comment]
Oh I didn't know you literally meant just replace it with that line haha

**Comment by Shadowfita** [comment]
yeah, haha.

**Comment by Shadowfita** [comment]
Lots of people are requesting an ODST background movie.

**Comment by TheFeelTrain** [comment]
That would be awesome but I can't seem to find one. I just got really lucky finding the others. The default Halo Reach one was literally just off some random French website. If you know a way to get the Halo 2,3, or ODST ones let me know.

**Comment by Shadowfita** [comment]
You should totally put a little 'by thefeeltrain and Orion' somewhere ;D but put mostly you cause you did all the amazing work haha, or just you.

**Comment by Shadowfita** [comment]
The gametype icons look like this when overlayed http://puu.sh/iHUdz/e61b317989.jpg

**Comment by TheFeelTrain** [comment]
Who's Orion? Is that you? and I guess Awesomium doesn't support the background set to no-repeat for some reason. I can fix it but that sucks.

**Comment by Shadowfita** [comment]
Yeah I'm Orion in the IRC and ingame.

**Comment by TheFeelTrain** [comment]
There should be fixed now. Just download the new dewrito.css

**Comment by Shadowfita** [comment]
the gametype icons?

**Comment by TheFeelTrain** [comment]
Yes

**Comment by Shadowfita** [comment]
Awesome.

**Comment by TheFeelTrain** [comment]
FishPhd just posted my menu in action on Twitter, It looks awesome. But is there any reason why it's so bright and the logo is missing? I hope we can fix that. https://t.co/iHApyfQk6Z

**Comment by Shadowfita** [comment]
The brightness is because of the overlay, it'll be fixed in the future I hope and the logo is probably just a bug too.

I sent you this link earlier, https://imgrush.com/NFBa0Okzh6JS not sure if you saw it :p

**Comment by TheFeelTrain** [comment]
The logo might be something on my end actually, I'll look into it. Also I don't know if you noticed but I added Credits to the main menu.

**Comment by Shadowfita** [comment]
Do you think, for the server browser part you could add filters for map and gametype? I can then do the javascript side of it.

**Comment by TheFeelTrain** [comment]
Is it even necessary? I doubt there will ever be more than 15 servers at once anyways. But if you really want it I can do that tomorrow.

**Comment by TheFeelTrain** [comment]
Wrong button

**Comment by Shadowfita** [comment]
I believe that will be the case in the future, a few people recommended it, fish and personality.

**Comment by Shadowfita** [comment]
Uncaught Error: Syntax error, unrecognized expression: [data-map='Hide N'Sneak']

Doesn't seem to like modded names when trying to join

**Comment by Shadowfita** [comment]
Also, did you remove my mapclassname to name thing?

**Comment by Shadowfita** [comment]
http://puu.sh/iIiQd/9f3562287e.txt

This will fix the custom map stuff and display the correct images when people have different variants of the same maps.

**Comment by TheFeelTrain** [comment]
Hide N' Seek probably didn't work because of the apostrophe. It would work with [data-map="Hide N'Sneak"] so it doesn't conflict. And sorry I removed most of the commented stuff to clean it up a bit. Added the new map code.

**Comment by Shadowfita** [comment]
I've encountered an issue when joining servers. $(".server").data("server") is returning the wrong index number when you join a server that isn't at the top of the list.

http://puu.sh/iITGT/74dadd31f2.png
http://puu.sh/iITHH/f3bd62317c.png

the only way I can think of fixing it is by having a hidden ip address in some div on the page and set that when joining then read that when joining game.

**Comment by Shadowfita** [comment]
Okay I believe I fixed it.

http://puu.sh/iIWfE/6cfab62481.txt

**Comment by Shadowfita** [comment]
Should we have it so it loads all the .js and .css from a url so that when we make changes they dont have to re-download it?

**Comment by Shadowfita** [comment]
https://imgrush.com/50upXw6Lf9KX Kill death ratio :3

**Comment by TheFeelTrain** [comment]
You could have them set their js/css to the GitHub links (http://thefeeltrain.github.io/js/dewrito.js) or maybe we should add that as setting - either local or GitHub files. And they would still have to download a new index.html no matter what since that's the main file. The thing is, as we're editing them we can't test the changes until we commit it, so that wouldn't be optimal.
