### ISSUE TITLE
Version number saved in the cookie?!

### ISSUE THREAD

**Issue by scooterpsu** [thefeeltrain/thefeeltrain.github.io#15]
Many people are having issues in-game that their version number is wrong (can't join games because of it). Clearing the cookies fixes this.

The problem is, the version number is being saved in the cookie, and it doesn't always update.

Why in the world is that saved in the cookie?! It makes perfect sense to poll the game for that, and then you don't hit issues like this.

**Comment by TheFeelTrain** [comment]
The version number gets pulled from http://eriq.co/eldewrito/update, so I have no idea why it would be saved in a cookie. I'll let Orion know.

**Comment by scooterpsu** [comment]
I don't mean the overall version, I mean the version of the client it's running on (0.4.9.0). This is the one it's comparing against the version of the host, to verify if it can join or not.

It's defaulting to 0.0.0.0 when the menu loads, and sometimes doesn't get overwritten... so the menu tells the player that they can't join the game because they have a different version (which they don't).

This is the bit that doesn't make sense to write to the cookie.

**Comment by TheFeelTrain** [comment]
Alright, should be good for now. I removed the check code until Orion sorts it out.
