### ISSUE TITLE
Feeltrain's cache server is no longer functioning

### ISSUE THREAD

**Issue by Red-M** [thefeeltrain/thefeeltrain.github.io#20]
As per the title this is currently broken.
I have a fork that will work off of the normal master sevrers if that is acceptable to be merged, however I have left the friends and party integration non-functional.

**Comment by Shadowfita** [comment]
It's working perfectly fine. 

http://158.69.166.144:8081/

http://halo.thefeeltra.in/

Is functioning correctly.

**Comment by Red-M** [comment]
It wasn't working last week, oh well.
Take the repo's implementation if you want so there is a fallback.

**Comment by Shadowfita** [comment]
Thank you.
