### ISSUE TITLE
Connecting to server should fail if different version

### ISSUE THREAD

**Issue by dark-c0de** [thefeeltrain/thefeeltrain.github.io#7]
Currently if connecting to a server fails, it looks like the game is trying to join forever without failing back to the server browser.

You should check the latest messages and make sure messages like "Server is running a different ElDewrito version." aren't there.

**Comment by Irock23** [comment]
A Game.Version command was added. It could just compare the servers' versions against that.

**Comment by Shadowfita** [comment]
Will add now.

**Comment by dark-c0de** [comment]
Take note of the new notification system.

```
       $.snackbar({content:'Connected!'});
```

You can use this to alert the user it failed to connect.

**Comment by Shadowfita** [comment]
How new is Game.Version?

**Comment by dark-c0de** [comment]
https://github.com/ElDewrito/ElDorito/commit/099f13ebeb5849c5f4b235ac1c36a48a95d8e007

So 0.4.9.240
