### ISSUE TITLE
When changing background too many times too fast, the backgrounds fail to load at all.

### ISSUE THREAD

**Issue by fegkay15** [thefeeltrain/thefeeltrain.github.io#8]
When I typically fly through the settings that change the background (preset or background changer) the background webms don't load and the only way to view them again is to reload the page(in browser) or press F11 to close and F11 again to reopen(in game). Occurs in browser and in game.

**Comment by Shadowfita** [comment]
We're aware.

**Comment by fegkay15** [comment]
Ok. Wasn't aware if it was just me or it happens to everybody.
